# Generated by Django 4.1.2 on 2023-04-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.CharField(max_length=200)),
                ('s_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('sclass', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('s_date', models.CharField(max_length=200)),
                ('e_date', models.CharField(max_length=200)),
            ],
        ),
    ]
