# Generated by Django 4.1.2 on 2023-04-01 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_booking_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='e_date',
            new_name='e_time',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='s_date',
            new_name='s_time',
        ),
    ]
