# Generated by Django 4.1.2 on 2023-04-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_rename_e_date_booking_e_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tfee',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='tmobile',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='tname',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='tplace',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
