# Generated by Django 4.1.2 on 2023-03-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_register',
            name='fee',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
