# Generated by Django 4.1.2 on 2023-04-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_teacher_register_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_register',
            name='image',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
