# Generated by Django 4.1.2 on 2023-04-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_teacher_register_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_register',
            name='image',
            field=models.ImageField(max_length=300, upload_to=''),
        ),
    ]
