# Generated by Django 4.1.2 on 2023-04-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='app_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=200)),
                ('r_date', models.CharField(max_length=200)),
            ],
        ),
    ]
